version: '3'

services:
  backend:
    build:
      context: .
    network_mode: "host"

  proxy:
    build:
      context: tools/apache-hosts
#    environment:
#      - HOST=example.com
    network_mode: "host"
